export interface CalculationItem {
  [key: string]: number | string | boolean | undefined;
  addedAt: number;
  avgGoldPerDay: number;
  customSellPrice: number;
  displayCategory: string;
  foodFarmingBuff: number;
  itemId: string;
  isCustom: boolean;
  name: string;
  sellPrice: number;
  quality: string;
  isCask: boolean;
  cropId?: string;
  // processingTime?: number;
  // ingredientId?: string;
  // quality?: string;
  // priceMultiplier?: number;
  // perkSellPriceMultiplier?: number;
  // processingTimeInDays?: number;
  // processingTimeInDaysModified?: number;
  // basePrice?: number;
  // normalSellPrice?: number;
  // baseSellPricePerHarvest?: number;
  // farmingLevelAvgPriceMultiplier?: number;
  // sellPricePerHarvestRounded?: number;
  // cropId?: string;
  // startQuality: string;
  // quantity?: number;
  // eggQuality?: string;
}
